# Generated by Django 4.1.2 on 2022-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_snippet_snippets_rename_todo_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=10.55)),
                ('brand', models.ImageField(upload_to='image')),
                ('image', models.ImageField(upload_to='image')),
                ('stock_aval', models.BooleanField(null=True)),
            ],
        ),
    ]
