# Generated by Django 4.1.2 on 2022-11-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_aval',
        ),
    ]
